export enum ProfileScreens {
    EditProfile = "EditProfile",
    EditInstructorProfile = "EditInstructorProfile",
    ResolveApplications = "ResolveApplications",
    DrivingSchoolProfile = "DrivingSchoolProfile",
    LanguagePreferences = "LanguagePreferences",
    NotificationPreferences = "NotificationPreferences",
}

export enum Screens {
    NewEquation = "NewEquation",
    Authenticate = "Authenticate",
    NestedAuthenticate = "NestedAuthenticate",
    NestedDashboard = "NestedDashboard",
    Dashboard = "Dashboard",
    NestedProfile = "NestedProfile",
    Profile = "Profile",
    MyEquations = "MyEquations",
    InstructorProfile = "InstructorProfile",
    Instructors = "Instructors",
    DrivingSchoolProfile = "DrivingSchoolProfile",
    ReserveRideList = "ReserveRideList",
    Notifications = "Notifications",
    PasswordReset = "PasswordReset",
    Manage = "Manage",
    NestedManage = "NestedManage",
    GroupLessons = "GroupLessons",
    GroupStudents = "GroupStudents",
    NestedAdminDashboard = "NestedAdminDashboard",
    AdminDashboard = "AdminDashboard",
    AdminRides = "AdminRides",
    AdminLessons = "AdminLessons",
    AdminResolvedRides = "AdminResolvedRides",
    EditRide = "EditRide",
    StudentProfile = "StudentProfile",
    GroupProfile = "GroupProfile",
    StudentRides = "StudentRides",
    StudentLessons = "StudentLessons",
    EditProfile = "EditProfile",
    EditInstructorProfile = "EditInstructorProfile",
    LanguagePreferences = "LanguagePreferences",
    NotificationPreferences = "NotificationPreferences",
    ResolveApplications = "ResolveApplications",
    NestedConversations = "NestedConversations",
    Conversations = "Conversations",
    Chat = "Chat",
    ChatDetails = "ChatDetails",
    ChatMembers = "ChatMembers",
    TempChat = "TempChat",
}
